main:
  - name: About
    url: /
    weight: 10

  - name: Institutional Experience
    url: experience/
    weight: 20

  - name: Projects
    url: projects/
    weight: 30

  - name: News
    url: /#news
    weight: 40